
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zero_one_task1
    username: postgres
    password: Sobirov0717
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate.format_sql: true
server:
  port: 80